### ISSUE TITLE
Preserve Rust toolchain after wasm plugin `preBuild`

### ISSUE THREAD

**Issue by TyceHerrman** [luccahuguet/yazelix#625]
### Yazelix version diagnostics

{
  "runtime_dir": "/nix/store/5yqpc93vzbdbq8d7mfdjx3gbx0jyaqw3-yazelix",
  "runtime_identity": {
    "inputs": {
      "fenix": {
        "last_modified_date": "20260531090325",
        "revision": "96e0fc9f1a9b37f6477fa11c3fd48575354773ed",
        "short_revision": "96e0fc9"
      },
      "home_manager": {
        "last_modified_date": "20260424041912",
        "revision": "6012cf1fed3eba66115f3fd117b9be6bd2a15b2f",
        "short_revision": "6012cf1"
      },
      "nixpkgs": {
        "last_modified_date": "20260521081518",
        "revision": "4a29d733e8a7d5b824c3d8c958a946a9867b3eb2",
        "short_revision": "4a29d73"
      },
      "yazelix_cursors": {
        "last_modified_date": "20260608172211",
        "revision": "3047edb0e1b64bc663c195e9b29b57bdce0b8112",
        "short_revision": "3047edb"
      },
      "yazelix_helix": {
        "last_modified_date": "20260606170455",
        "revision": "961c4ba4573ffbf84b0f925be047dec2fa7a6c6c",
        "short_revision": "961c4ba"
      },
      "yazelix_screen": {
        "last_modified_date": "20260607180444",
        "revision": "6b1ec1b8a435e2519b5f95d859804fe17230e4b2",
        "short_revision": "6b1ec1b"
      },
      "yazelix_terminal": {
        "last_modified_date": "20260607151048",
        "revision": "ebb1c6096e2238db38544f550f110a6b04d3c82f",
        "short_revision": "ebb1c60"
      },
      "yazelix_yazi_assets": {
        "last_modified_date": "20260601164303",
        "revision": "a9f80529b634f4ec5fe3fddb5e83c548e8847618",
        "short_revision": "a9f8052"
      },
      "yazelix_zellij_bar": {
        "last_modified_date": "20260606050204",
        "revision": "33ba0ce2129876aa787b025b6b65a6315b1d0a26",
        "short_revision": "33ba0ce"
      },
      "yazelix_zellij_pane_orchestrator": {
        "last_modified_date": "20260607125840",
        "revision": "311ef35d47b68236377284e592856d5355fdc856",
        "short_revision": "311ef35"
      },
      "yazelix_zellij_popup": {
        "last_modified_date": "20260607172954",
        "revision": "1a658d8e7b0a9413382b57089294b6d0d4c31dbf",
        "short_revision": "1a658d8"
      }
    },
    "runtime_variant": "ghostty",
    "schema_version": 1,
    "source": {
      "last_modified_date": "19700101000000",
      "revision": null,
      "short_revision": null
    },
    "version": "v17.5"
  },
  "schema_version": 1,
  "version": "v17.5"
}

### Details

Failure:

```text
error[E0463]: can't find crate for `std`
= note: the `wasm32-wasip1` target may not be installed
```

Affected derivations:

- `yazelix-zellij-popup`
- `yazelix-zellij-pane-orchestrator`

Observed cause: Darwin build hooks run before `cargo build --target wasm32-wasip1` and can leave Cargo/Rust env resolving to a Rust toolchain without `wasm32-wasip1` std/core.

Needed upstream fix:

- Save `CARGO`, `RUSTC`, and `PATH` before `runHook preBuild`.
- Restore them immediately after `runHook preBuild`.
- Set `CARGO_BUILD_RUSTC="$RUSTC"`.
- Set `CARGO_TARGET_WASM32_WASIP1_RUSTC="$RUSTC"`.
- Build wasm plugins with stable toolchain env, ideally in the plugin package itself rather than downstream `overrideAttrs`.

Local workaround also uses `cargo build -j 1` for these wasm plugin builds, because parallel Rust invocations made the failure intermittent and package-specific.

## Local verification

Local downstream patch passed:

```text
darwin-rebuild build -L
```

Build completed through:

- `zjstatus`
- `yazelix-zellij-popup`
- `yazelix-zellij-pane-orchestrator`
- `yazelix-runtime`
- `darwin-system`

**Comment by luccahuguet** [comment]
Automated: Tracked in Beads as `yazelix-fhfdu`.

**Comment by luccahuguet** [comment]
Agent context: posted by Lucca's Codex coding agent on behalf of the Yazelix maintainers. Model: GPT-5.5. Effort: xhigh. Surface: Codex.

Fix summary:

This bug is the same Darwin-only failure family Tyce diagnosed in #604: the Zellij wasm plugin packages can enter the normal Cargo hook path before the wasm-capable Fenix toolchain is selected, so `cargo build --target wasm32-wasip1` may resolve a Rust toolchain without the `wasm32-wasip1` standard library and fail with `error[E0463]: can't find crate for std/core`.

The child package fix is intentionally small and child-owned:

- keep `dontCargoBuild = true` so the default host-target `cargoBuildHook` does not perform the plugin build
- run `runHook preBuild`
- immediately after `preBuild`, pin `CARGO`, `RUSTC`, and `PATH` to the combined Fenix wasm-capable toolchain
- export `CARGO_BUILD_RUSTC="$RUSTC"`, which Cargo documents as the build rustc selector
- check `rustc --print target-libdir --target wasm32-wasip1` before the build so a missing wasm std fails directly
- run one serialized manual build with `cargo build -j 1 --target wasm32-wasip1`
- keep installing the generated `.wasm` manually and keep the non-empty wasm install check

Fresh-eyes correction: I removed the originally proposed `CARGO_TARGET_WASM32_WASIP1_RUSTC` export before publishing because Cargo documents target-specific env vars for linker/runner/rustflags, but not target-specific rustc selection. The real rustc pin is `CARGO_BUILD_RUSTC` plus the explicit `RUSTC`, `CARGO`, and `PATH` exports.

Published commits:

- `luccahuguet/yazelix-zellij-popup@c7646b157a18bf5826567cee30a02d432cd94734`
- `luccahuguet/yazelix-zellij-pane-orchestrator@4d5d4533e258a7c39f326b2ffa3de86052242f64`
- `luccahuguet/yazelix@3569c1c2` consumes both child fixes in `flake.lock`

Validation passed before pushing main:

- `cargo fmt --manifest-path rust_core/Cargo.toml --all -- --check`
- `cargo test --manifest-path rust_core/Cargo.toml -p yazelix_maintainer zellij_plugin_wasm_contract -- --nocapture`
- `yzx_repo_validator validate-child-release-transaction`
- `nix build .#runtime_ghostty --no-link --no-write-lock-file --accept-flake-config`

Confidence is high for this exact failure class, but we should keep the issue open until Tyce confirms a real `aarch64-darwin` Home Manager build passes.

**Comment by luccahuguet** [comment]
There goes Tyce again, doing the Lord's work

Appreciate it, man 🙏🏼

**Comment by luccahuguet** [comment]
Closing after maintainer approval. The published child package fixes and main flake.lock update are recorded above, with validation evidence for the wasm toolchain/preBuild failure class.

**Comment by TyceHerrman** [comment]
@luccahuguet I think this needs re-opened

I retested current `main` at `3569c1c21d6acf2cca33302bc46cb871b9ad7de1` after removing my downstream wasm-plugin override.

The failure is improved/narrower, but not fully gone on Darwin:

```text
error[E0463]: can't find crate for `core`
  |
  = note: the `wasm32-wasip1` target may not be installed
  = help: consider downloading the target with `rustup target add wasm32-wasip1`

error: could not compile `litemap` (lib) due to 1 previous error
error: builder for '...-yazelix-zellij-pane-orchestrator-0.1.0.drv' failed with exit code 101
```

What changed compared with the earlier failure:

- Latest upstream now fetches/builds `rust-std-1.96.0-wasm32-wasip1`.
- The failure now reproduces specifically in `yazelix-zellij-pane-orchestrator`.
- The failing crate in my latest run was `litemap`.
- The old downstream `cargo build -j 1` workaround is no longer valid because upstream now already passes jobs; injecting another `-j` causes `error: the argument '--jobs <N>' cannot be used multiple times`.

So the remaining issue looks like the wasm std is present in the build closure, but the pane-orchestrator Cargo invocation still resolves a Rust/Cargo environment that cannot see that `wasm32-wasip1` std/core.

The downstream workaround that still applies is now only the environment restore after `runHook preBuild`:

```sh
yazelix_saved_cargo="$CARGO"
yazelix_saved_rustc="$RUSTC"
yazelix_saved_path="$PATH"

runHook preBuild

export CARGO="$yazelix_saved_cargo"
export RUSTC="$yazelix_saved_rustc"
export PATH="$yazelix_saved_path"
export CARGO_BUILD_RUSTC="$yazelix_saved_rustc"
export CARGO_TARGET_WASM32_WASIP1_RUSTC="$yazelix_saved_rustc"
```

With that env-only override, I can get past the missing `core` / `wasm32-wasip1` failure locally. Without it, `yazelix-zellij-pane-orchestrator` still fails as above.

**Comment by luccahuguet** [comment]
Agent context: posted by Lucca's Codex coding agent on behalf of the Yazelix maintainers. Model: GPT-5.5. Effort: xhigh. Surface: Codex.

Reopening based on Tyce's Darwin retest on main@3569c1c2. The previous fix narrowed the failure but did not fully eliminate it: pane-orchestrator can still lose access to wasm32-wasip1 std/core after preBuild unless the original Nix-provided CARGO/RUSTC/PATH are saved before runHook preBuild and restored afterward. We are treating the manual post-preBuild reconstruction as insufficient and moving the child packages to preserve the original Nix Rust environment across preBuild.

**Comment by luccahuguet** [comment]
Agent context: posted by Lucca's Codex coding agent on behalf of the Yazelix maintainers. Model: GPT-5.5. Effort: xhigh. Surface: Codex.

Thanks for the retest. Reopening was correct.

Second-pass fix:

The previous fix selected the Fenix wasm toolchain only after `runHook preBuild`. That was not strong enough on Darwin: pane-orchestrator could still end up with Cargo/Rust state that could not see `wasm32-wasip1` std/core.

The child packages now preserve the selected wasm-capable toolchain across `preBuild` instead:

- set `CARGO`, `RUSTC`, and `PATH` to the combined Fenix toolchain before `runHook preBuild`
- save those selected values
- run `runHook preBuild`
- restore the saved `CARGO`, `RUSTC`, and `PATH`
- export `CARGO_BUILD_RUSTC="$RUSTC"`
- check `rustc --print target-libdir --target wasm32-wasip1`
- run one serialized manual `cargo build -j 1 --target wasm32-wasip1`

I also changed the child/main metadata contract from `wasmToolchainPinnedAfterPreBuild` to `wasmToolchainPreservedAcrossPreBuild`, so the main release validator rejects the weaker first-pass shape.

Published commits:

- `luccahuguet/yazelix-zellij-popup@b16a6835c7d641c80ed169d2da9fd20739af9030`
- `luccahuguet/yazelix-zellij-pane-orchestrator@405e8b22006464046c7d09f1e0545ef4e8cd0845`
- `luccahuguet/yazelix@37d8f41a` consumes both second-pass child fixes

Validation passed:

- `nix build .#yazelix_zellij_popup --no-link --no-write-lock-file`
- `nix build .#yazelix_zellij_pane_orchestrator --no-link --no-write-lock-file`
- `cargo fmt --manifest-path rust_core/Cargo.toml --all -- --check`
- `cargo test --manifest-path rust_core/Cargo.toml -p yazelix_maintainer zellij_plugin_wasm_contract -- --nocapture`
- `yzx_repo_validator validate-child-release-transaction`
- `nix build .#runtime_ghostty --no-link --no-write-lock-file --accept-flake-config`

Keeping this open until the real `aarch64-darwin` Home Manager build is confirmed.

**Comment by TyceHerrman** [comment]
I retested current `main` at `81f391f29d67e8442150c9c497e4e06fb41419df` after removing my downstream wasm-plugin override.

The failure is improved/narrower, but not fully gone on Darwin.

Current failure:

```text
Rust toolchain is missing wasm32-wasip1 std at /nix/store/h2nzavna70y30b957hfmn86jqnrfdjv3-rust-mixed/lib/rustlib/wasm32-wasip1/lib
error: builder for '...-yazelix-zellij-pane-orchestrator-0.1.0.drv' failed with exit code 1
```

What changed compared with the earlier failure:

- Latest upstream now fails earlier with an explicit toolchain check instead of later as `error[E0463]: can't find crate for core`.
- The failure now reproduces specifically in `yazelix-zellij-pane-orchestrator`.
- The old downstream `cargo build -j 1` workaround is no longer valid because upstream now already passes jobs; injecting another `-j` causes `error: the argument '--jobs <N>' cannot be used multiple times`.

So the remaining issue looks like the pane-orchestrator package still receives a `rust-mixed` toolchain without `wasm32-wasip1` std, even though the build is supposed to be using a wasm-capable Rust toolchain.

The downstream workaround that still applies is now only the environment restore after `runHook preBuild`:

```sh
yazelix_saved_cargo="$CARGO"
yazelix_saved_rustc="$RUSTC"
yazelix_saved_path="$PATH"

runHook preBuild

export CARGO="$yazelix_saved_cargo"
export RUSTC="$yazelix_saved_rustc"
export PATH="$yazelix_saved_path"
export CARGO_BUILD_RUSTC="$yazelix_saved_rustc"
export CARGO_TARGET_WASM32_WASIP1_RUSTC="$yazelix_saved_rustc"
```

With that env-only override, I can get past the missing `wasm32-wasip1` std failure locally. Without it, `yazelix-zellij-pane-orchestrator` still fails as above.

**Comment by luccahuguet** [comment]
Agent context: posted by Lucca's Codex coding agent on behalf of the Yazelix maintainers. Model: GPT-5.5. Effort: xhigh. Surface: Codex.

Third-pass fix is published.

Tyce's latest retest on main@81f391f2 proved the second-pass guard was now failing earlier, but still against the wrong Rust toolchain path: the package preserved the raw Fenix rustToolchain path, while the working downstream workaround preserved the Nix build environment's Cargo/Rustc/PATH before preBuild.

This pass changes both child packages to preserve the Nix-provided Rust toolchain instead:

- capture CARGO/RUSTC from the build environment before runHook preBuild, falling back to command -v cargo/rustc when the variables are unset
- save PATH before preBuild
- run runHook preBuild
- restore the saved CARGO/RUSTC/PATH
- export CARGO_BUILD_RUSTC=""
- keep the explicit wasm32-wasip1 target-libdir guard and serialized cargo build
- rename the child passthru metadata field to preBuildPreservesNixRustToolchain so the main validator rejects the weaker second-pass contract

Published commits:

- luccahuguet/yazelix-zellij-pane-orchestrator@d43475c77451abcd606e865614ede963e01a4743
- luccahuguet/yazelix-zellij-popup@d93acc835c7af43f67b76da77159f28e6c2f6807
- luccahuguet/yazelix@6bd909c4 consumes both child fixes

Validation passed:

- nix build .#yazelix_zellij_pane_orchestrator --no-link --no-write-lock-file
- nix build .#yazelix_zellij_popup --no-link --no-write-lock-file
- cargo fmt --manifest-path rust_core/Cargo.toml --all -- --check
- cargo test --manifest-path rust_core/Cargo.toml -p yazelix_maintainer zellij_plugin_wasm_contract -- --nocapture
- nix eval .#packages.aarch64-darwin.yazelix_zellij_pane_orchestrator.passthru.zellijPluginWasmPackageContract --json --no-write-lock-file
- nix eval .#packages.aarch64-darwin.yazelix_zellij_popup.passthru.zellijPluginWasmPackageContract --json --no-write-lock-file
- cargo run --manifest-path rust_core/Cargo.toml -p yazelix_maintainer --bin yzx_repo_validator -- validate-child-release-transaction
- nix build .#runtime_ghostty --no-link --no-write-lock-file --accept-flake-config

Keeping this open until a real aarch64-darwin Home Manager build confirms it.

**Comment by luccahuguet** [comment]
Agent context: posted by Lucca Codex coding agent on behalf of the Yazelix maintainers. Model: GPT-5.5. Effort: xhigh. Surface: Codex.

Future plan note:

The immediate fix above keeps the current shipped architecture working: child repos build their wasm packages, and Yazelix consumes those package outputs through the main flake lock.

There is also a better long-term architecture to evaluate. The old model avoided this Darwin failure class because the main repo consumed already-built wasm, but it did that by carrying copied first-party wasm binaries in the main repo, which created provenance and sync-drift problems.

The possible third option is:

- child repos continue to own source, source builds, CI checks, standalone examples, and release provenance
- child repos also publish or package a child-owned wasm artifact
- main Yazelix consumes that child-owned wasm artifact instead of checked-in main-repo wasm
- normal Yazelix users do not have to rebuild Rust wasm plugins from source on every host
- source builds remain child CI/release responsibilities and local development still uses explicit source override paths

That would keep the useful part of consuming wasm artifacts without returning to main-repo copied binaries. It should also reduce the chance that regular Darwin/Linux users hit Rust wasm toolchain packaging failures for target-agnostic Zellij plugin wasm.

Tracked internally as Beads decision: `yazelix-child-owned-prebuilt-zellij-wasm-t615x`.

**Comment by luccahuguet** [comment]
and if it keeps presenting problems, we merge the child-repos back into the main repo

**Comment by TyceHerrman** [comment]
I retested current `main` at `638279f2bcc344073d42a20eb8cfc0463f2fc885` after removing my downstream wasm-plugin workaround.  the previous `wasm32-wasip1` failure is gone for me on Darwin. The build now gets past the Yazelix plugin builders and successfully compiles through bundled `zellij-0.44.3`:

```text
Finished `release` profile [optimized] target(s) in 12m 26s
Executing cargoInstallPostBuildHook
Finished cargoInstallPostBuildHook
Finished cargoBuildHook
buildPhase completed in 12 minutes 29 seconds
Running phase: installPhase
Executing cargoInstallHook
Finished cargoInstallHook
Running phase: fixupPhase
```

The full system build still did not complete, but the remaining blocker is different: it hung during the Darwin fixup strip step for bundled `zellij`:

```text
stripping (with command strip and flags -S) in /nix/store/...-zellij-0.44.3/bin
```

This looks like the same Darwin strip-tooling family of issues I filed upstream as https://github.com/NixOS/nixpkgs/issues/527614. This new run has the same failure boundary, but the affected package is bundled `zellij` instead.

Current bundled `zellij` details:

- Failing derivation: `/nix/store/ss8689df1p7qpwi94rcnyf6j716w20i4-zellij-0.44.3.drv`
- Output path: `/nix/store/3bgrv225mgsxvrcsfdigrdrlhxb0rrri-zellij-0.44.3`
- Stripped file: `/nix/store/3bgrv225mgsxvrcsfdigrdrlhxb0rrri-zellij-0.44.3/bin/zellij`
- `bin/` contained only that `zellij` binary
- Binary metadata: `Mach-O 64-bit executable arm64`, about `41M`
- Strip executable seen live: `/nix/store/z61v8rpy6ammvikrpcihn3ij8rrqk0bz-cctools-binutils-darwin-1010.6/bin/strip`
- Parent pipeline seen live: `xargs ... -- strip -S`

I terminated the stuck `strip` child after it sat there for more than 10 minutes, so the final failure was caused by my termination:

```text
error: builder for '/nix/store/...-zellij-0.44.3.drv' failed with exit code 1
Terminated: 15 find $paths ... | xargs -r -0 -n1 -P "$NIX_BUILD_CORES" -- $cmd $stripFlags
```

So from my side, the wasm toolchain/Cargo environment issue this report was tracking appears fixed on current `main`. The only remaining local blocker is the separate macOS/Darwin `strip` hang while packaging bundled `zellij` - could be opened as new issue.

If Yazelix wants a local package-side workaround for Darwin while the Nixpkgs issue is still open, the likely shape is the same narrow workaround as before: avoid stripping the affected Darwin binary, rather than changing the Rust build.

**Comment by TyceHerrman** [comment]
Correction to my earlier local result: the wasm issue is **not** fixed for me on Darwin when the downstream workaround is removed.

Current no-workaround failure:

```text
error[E0463]: can't find crate for `core`
  |
  = note: the `wasm32-wasip1` target may not be installed
  = help: consider downloading the target with `rustup target add wasm32-wasip1`

error: could not compile `yoke` (lib) due to 1 previous error
error: builder for '/nix/store/bxx4xfkhbfv46w148bdrdx14qaj6xsnl-yazelix-zellij-pane-orchestrator-0.1.0.drv' failed with exit code 101
```

So the remaining wasm failure is still in `yazelix-zellij-pane-orchestrator-0.1.0`. The crate visible at the failure point in this run was `yoke`, but the failure boundary is the same: Cargo/rustc is trying to build for `wasm32-wasip1` without the target std/core available to that invocation.

The build did not reach bundled `zellij` stripping in this no-workaround run.

For completeness, when I previously got past the wasm plugin failure with a downstream workaround, the next separate blocker was Darwin strip tooling while packaging bundled `zellij-0.44.3`:
in


Current summary:

- The wasm toolchain/Cargo environment issue is still the first blocker without downstream patches.
- The bundled `zellij` Darwin strip hang is a separate second blocker that only becomes visible after the wasm plugin build gets past `yazelix-zellij-pane-orchestrator`.
- A likely local workaround for the strip side is Darwin-only `dontStrip = true` for the bundled `zellij` package, but that does not address the wasm failure.

**Comment by luccahuguet** [comment]
Agent context: posted by Lucca Codex coding agent on behalf of the Yazelix maintainers. Model: GPT-5.5. Effort: xhigh. Surface: Codex.

Fourth-pass fix is published.

Tyce corrected the no-workaround Darwin result: main@638279f2 still failed first in `yazelix-zellij-pane-orchestrator` with missing `wasm32-wasip1` core, this time while compiling `yoke`. The remaining practical delta from the downstream workaround was the target-specific Rustc env var.

This pass keeps the third-pass Nix Rust environment preservation and adds the missing env pin:

```sh
export CARGO_BUILD_RUSTC="$RUSTC"
export CARGO_TARGET_WASM32_WASIP1_RUSTC="$RUSTC"
```

The child package contract now also requires `wasmTargetRustcEnvPinned = true`, so main rejects child package metadata that omits this fourth-pass hardening.

Published commits:

- `luccahuguet/yazelix-zellij-pane-orchestrator@c935bcb1bf4275749f2a82150bb243035d90c3f9`
- `luccahuguet/yazelix-zellij-popup@8c79095a5623e1207be601f4cdb8624612bfde84`
- `luccahuguet/yazelix@543c285c` consumes both child fixes

Validation passed:

- `nix build .#yazelix_zellij_pane_orchestrator --no-link --no-write-lock-file`
- `nix build .#yazelix_zellij_popup --no-link --no-write-lock-file`
- `cargo fmt --manifest-path rust_core/Cargo.toml --all -- --check`
- `cargo test --manifest-path rust_core/Cargo.toml -p yazelix_maintainer zellij_plugin_wasm_contract -- --nocapture`
- `nix eval .#packages.aarch64-darwin.yazelix_zellij_pane_orchestrator.passthru.zellijPluginWasmPackageContract --json --no-write-lock-file`
- `nix eval .#packages.aarch64-darwin.yazelix_zellij_popup.passthru.zellijPluginWasmPackageContract --json --no-write-lock-file`
- `cargo run --manifest-path rust_core/Cargo.toml -p yazelix_maintainer --bin yzx_repo_validator -- validate-child-release-transaction`
- `nix build .#runtime_ghostty --no-link --no-write-lock-file --accept-flake-config`

Keeping this open for a real aarch64-darwin no-workaround retest.

Separate note: the bundled `zellij` Darwin strip hang Tyce saw after applying his local wasm workaround is a distinct second blocker. If it reproduces after this wasm fix, it should be tracked separately from this wasm toolchain issue.

**Comment by TyceHerrman** [comment]
I think this is all fixed now. I'll open a new issue if it happens again
